import { describe, expect, it } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(process.cwd());
const read = (relativePath: string) => readFileSync(resolve(root, relativePath), 'utf8');

describe('Android packaging readiness', () => {
  it('keeps the web shell Android-safe and accessible', () => {
    const html = read('client/index.html');
    expect(html).toContain('viewport-fit=cover');
    expect(html).toContain('name="theme-color" content="#E87817"');
    expect(html).not.toContain('maximum-scale=1');
  });

  it('does not expose raw runtime diagnostics in the production UI', () => {
    const errorBoundary = read('client/src/components/ErrorBoundary.tsx');
    const bootstrap = read('client/src/main.tsx');
    expect(errorBoundary).not.toContain('<pre');
    expect(bootstrap).toContain('if (import.meta.env.DEV) console.error');
  });

  it('keeps the TWA and PWA release identities aligned', () => {
    const twa = JSON.parse(read('android-app/twa-manifest.json')) as {
      packageId: string;
      host: string;
      appVersionName: string;
      appVersionCode: number;
      startUrl: string;
      backgroundColor: string;
    };
    const pwa = JSON.parse(read('client/public/manifest.json')) as {
      display: string;
      start_url: string;
    };
    const gradle = read('android-app/app/build.gradle');
    const manifest = read('android-app/app/src/main/AndroidManifest.xml');
    const mainActivity = read('android-app/app/src/main/java/app/kharcha/splitter/MainActivity.java');
    const groupFundDetail = read('client/src/pages/GroupFundDetail.tsx');
    const sharedHomeDetail = read('client/src/pages/SharedHomeDetail.tsx');
    const tripDetail = read('client/src/pages/TripDetail.tsx');
    const tripReport = read('client/src/lib/tripReport.ts');
    const indexCss = read('client/src/index.css');
    const filepaths = read('android-app/app/src/main/res/xml/filepaths.xml');
    const pdfLayout = read('client/src/lib/pdfLayout.ts');

    expect(twa.packageId).toBe('app.kharcha.splitter');
    expect(twa.host).toBe('kharchasplit-rlsqgpta.manus.space');
    expect(twa.appVersionName).toBe('1.0.0');
    expect(twa.appVersionCode).toBe(63);
    expect(twa.startUrl).toBe('/?android=1');
    expect(twa.themeColor).toBe('#FFFAF2');
    expect(twa.backgroundColor).toBe('#FFFAF2');
    expect(existsSync(resolve(root, 'android-app/app/src/main/res/drawable-nodpi/kharcha_logo_mobile.webp'))).toBe(true);
    expect(pwa.display).toBe('standalone');
    expect(pwa.start_url).toBe('/');
    expect(gradle).toContain('targetSdkVersion 36');
    expect(gradle).toContain("launchUrl: '/?android=1'");
    expect(gradle).toContain("?: '63'");
    expect(gradle).toContain('validateReleaseSigning');
    expect(gradle).toContain("androidx.biometric:biometric:1.1.0");
    expect(manifest).toContain('android.permission.READ_CONTACTS');
    expect(manifest).toContain('android.permission.CAMERA');
    expect(mainActivity).toContain('onPermissionRequest');
    expect(mainActivity).toContain('RESOURCE_VIDEO_CAPTURE');
    expect(mainActivity).toContain('KharchaContacts');
    expect(mainActivity).toContain('pickContacts');
    expect(mainActivity).toContain('KharchaSecurity');
    expect(mainActivity).toContain('KharchaShare');
    expect(mainActivity).toContain('shareText');
    expect(mainActivity).toContain('BiometricPrompt');
    expect(mainActivity).toContain('BIOMETRIC_STRONG');
    expect(mainActivity).toContain('DEVICE_CREDENTIAL');
    expect(mainActivity).toContain('consumeDeviceAuthResult');
    expect(mainActivity).toContain('pending_device_auth_result');
    expect(mainActivity).toContain('KharchaPdf');
    expect(mainActivity).toContain('showReport');
    expect(mainActivity).toContain('showReportAction');
    expect(mainActivity).toContain('PrintManager');
    expect(mainActivity).toContain('savePdfReport');
    expect(mainActivity).toContain('reportReady');
    expect(mainActivity).toContain('onPageFinished');
    expect(mainActivity).toContain('protected void onResume()');
    expect(mainActivity).toContain("kharcha-app-resume");
    expect(mainActivity).toContain('setLayerType(View.LAYER_TYPE_SOFTWARE, null)');
    expect(mainActivity).toContain('setInitialScale(100)');
    expect(mainActivity).toContain('setUseWideViewPort(false)');
    expect(mainActivity).toContain('reportView');
    expect(mainActivity).toContain('sharePdfReport');
    expect(mainActivity).toContain('createPrintDocumentAdapter(safePdfLabel(title, "Kharcha report"))');
    expect(mainActivity).toContain('renderReportPdf(output, reportView)');
    expect(mainActivity).toContain('final int pageMargin = 40;');
    expect(mainActivity).toContain('final int printableWidth = pageWidth - (pageMargin * 2);');
    expect(mainActivity).toContain('final int printableHeight = pageHeight - (pageMargin * 2);');
    expect(mainActivity).toContain('launchPdfShare(outputFile, title);');
    expect(mainActivity).toContain('FileProvider.getUriForFile');
    expect(mainActivity).toContain('application/pdf');
    expect(mainActivity).toContain('pdfReportDialog.dismiss()');
    expect(groupFundDetail).toContain('KharchaPdf');
    expect(groupFundDetail).toContain('auditPdfBack');
    expect(groupFundDetail).toContain('auditPdfPrint');
    expect(groupFundDetail).toContain('auditPdfSave');
    expect(groupFundDetail).toContain('isAndroidShell');
    expect(groupFundDetail).toContain('handleSaveMemberAmount');
    expect(groupFundDetail).toContain("setSavedAmountInput(getSavedCollectionAmount(m)?.toString() ?? '')");
    expect(groupFundDetail).toContain("setSavedAmountInput('')");
    expect(groupFundDetail).toContain('setSelectedMemberForCollection(undefined)');
    expect(groupFundDetail).not.toContain("setCollectionAmount(amount.toString())");
    expect(groupFundDetail).not.toContain("setUpiInputAmount(amount.toString())");
    expect(groupFundDetail).toContain('auditPdfUnavailable');
    expect(groupFundDetail).toContain('escapePdfHtml');
    expect(groupFundDetail).toContain('KHARCHA_LOGO_LOCKUP');
    expect(groupFundDetail).toContain('PDF_LAYOUT_CSS');
    expect(pdfLayout).toContain('table-layout: fixed');
    expect(groupFundDetail).toContain('class="report-logo"');
    expect(pdfLayout).toContain('max-width: 100%');
    expect(pdfLayout).toContain('overflow-wrap: anywhere');
    expect(pdfLayout).toContain('word-break: break-word');
    expect(groupFundDetail).toContain('class="member-name"');
    expect(groupFundDetail).toContain('style="width: 28%;"');
    expect(groupFundDetail).toContain('style="width: 27%;"');
    expect(pdfLayout).toContain('white-space: normal');
    expect(groupFundDetail).toContain('bulkMessageSelectedIds');
    expect(groupFundDetail).toContain('handleSendBulkToAll');
    expect(groupFundDetail).toContain('handleSendBulkSelection');
    expect(groupFundDetail).toContain('getBulkMessageKind');
    expect(groupFundDetail).toContain('generateGroupFundWhatsAppThankYouUrl');
    expect(groupFundDetail).toContain("getPeriodCollectionStatus(fund.contributions, member.id, selectedPeriod)");
    expect(groupFundDetail).toContain("t('auditThankYouMessage' as any");
    expect(groupFundDetail).toContain('handleOpenNextBulkMessage');
    expect(groupFundDetail).toContain('auditSendToAll');
    expect(groupFundDetail).toContain('auditSendSelection');
    expect(groupFundDetail).toContain('auditBulkMessageQueueHelp');
    expect(groupFundDetail).toContain('bulkMessageAutoAdvanceAt');
    expect(groupFundDetail).toContain("document.addEventListener('visibilitychange'");
    expect(groupFundDetail).toContain("window.addEventListener('pageshow'");
    expect(groupFundDetail).toContain("window.addEventListener('kharcha-app-resume'");
    expect(groupFundDetail).toContain('w-[calc(100%-1rem)]');
    expect(groupFundDetail).toContain('overflow-x-hidden');
    expect(groupFundDetail).toContain('flex-col gap-2 sm:flex-row');
    expect(groupFundDetail).toContain('handleOpenNextBulkMessage();');
    expect(groupFundDetail).not.toContain('window.print();');
    expect(mainActivity).toContain('createPrintDocumentAdapter(safePdfLabel(title, "Kharcha report"))');
    expect(mainActivity).toContain('private void savePdfReport(WebView reportView, String title)');
    const saveMethodStart = mainActivity.indexOf('private void savePdfReport');
    const shareMethodStart = mainActivity.indexOf('private void sharePdfReport');
    const saveMethod = mainActivity.slice(saveMethodStart, shareMethodStart);
    expect(saveMethod).toContain('writePdfToDownloads(reportView, title);');
    expect(saveMethod).not.toContain('printPdfReport(reportView, title);');
    expect(mainActivity).toContain('MediaStore.Downloads.EXTERNAL_CONTENT_URI');
    expect(mainActivity).toContain('PDF saved to Downloads');
    expect(saveMethod).not.toContain('Choose Save as PDF to download');
    expect(mainActivity).not.toContain('openOutputStream(uri, "w")');
    expect(tripDetail).toContain('handleGeneratePdfReport');
    expect(tripDetail).toContain('buildTripReportModel');
    expect(tripDetail).toContain('KHARCHA_LOGO_LOCKUP');
    expect(tripDetail).toContain('KharchaPdf');
    expect(tripDetail).toContain('auditPdfPrint');
    expect(tripDetail).toContain('auditPdfSave');
    expect(tripDetail).toContain('<meta name="viewport" content="width=device-width, initial-scale=1.0">');
    expect(tripDetail).toContain('PDF_LAYOUT_CSS');
    expect(tripDetail).toContain('KharchaPdf');
    expect(tripDetail).toContain('overflow-x-hidden');
    expect(tripDetail).toContain('auditPaidBy');
    expect(tripDetail).toContain('settlementSummary');
    expect(tripReport).toContain('calculateMemberBalances');
    expect(tripReport).toContain('simplifySettlements');
    expect(tripReport).toContain('categoryRows');
    expect(tripDetail).toContain('bg-[#e7f0ea]');
    expect(tripDetail).toContain('min-h-12');
    expect(tripDetail).toContain('text-sm font-black');
    expect(tripDetail).toContain('data-[state=active]:bg-kharcha-green');
    expect(tripDetail).toContain('data-[state=active]:text-white');
    expect(indexCss).toContain('.android-trip-tabs [role="tab"][data-state="active"]');
    expect(indexCss).toContain('background-color: #d9f1e2 !important;');
    expect(indexCss).toContain('color: #18324b !important;');
    expect(indexCss).toContain('.android-trip-tabs [role="tab"][data-state="inactive"]');
    expect(sharedHomeDetail).toContain('handleGeneratePdfReport');
    expect(sharedHomeDetail).toContain('KharchaPdf');
    expect(sharedHomeDetail).toContain('auditPdfBack');
    expect(sharedHomeDetail).toContain('auditPdfPrint');
    expect(sharedHomeDetail).toContain('auditPdfSave');
    expect(sharedHomeDetail).toContain('sharedHomeShare');
    expect(sharedHomeDetail).toContain('isAndroidShell');
    expect(sharedHomeDetail).toContain('auditPdfUnavailable');
    expect(sharedHomeDetail).toContain('window.setTimeout');
    expect(sharedHomeDetail).toContain("{ id: 'recurring'");
    expect(sharedHomeDetail).not.toContain("{ id: 'bills'");
    expect(sharedHomeDetail).not.toContain("{ id: 'groceries'");
    expect(filepaths).toContain('shared-reports/');
  });
});
