import React, { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ChevronRight, Home as HomeIcon, Plus, Settings } from 'lucide-react';
import { useLocation, useRoute } from 'wouter';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { useLanguage } from '@/contexts/LanguageContext';
import SharedHomeExpenseDialog from '@/components/SharedHomeExpenseDialog';
import SharedHomeMemberDialog from '@/components/SharedHomeMemberDialog';
import SharedHomeRecurringDialog from '@/components/SharedHomeRecurringDialog';
import SharedHomeRentDialog from '@/components/SharedHomeRentDialog';
import { getSharedHomeById, saveSharedHome } from '@/sharedHome/storage';
import { buildRentPeriod, upsertRentPeriod } from '@/sharedHome/rentPersistence';
import { materializeRecurringExpenses, calculateMonthlyBalances, generatePendingHouseholdSettlements, getExpenseTotals, monthKeyFromDate } from '@/sharedHome/calculations';
import { sharedHomeCategoryLabel } from '@/sharedHome/categoryTranslations';
import type { HouseholdExpense, RecurringRule, RentConfig, SharedHome, SharedHomeMember } from '@/sharedHome/types';
import { nanoid } from 'nanoid';

type Tab = 'home' | 'expenses' | 'rent' | 'settlement';
const CATEGORY_VALUES=['Groceries','Electricity','Water','Internet','Gas / LPG','Maid / House Help','Cleaning','Repairs & Maintenance','Society / Maintenance Charges','Garbage / Waste','Food / Outside Food','Travel / Transport','Entertainment / Movies','Medical / Hospital','Household Items','Furniture / Appliances','Moving / Shifting','Delivery / Courier','Events / Parties','Other Shared Bills','Other'];
const money=(v:number)=>`₹${v.toLocaleString('en-IN',{maximumFractionDigits:2})}`;

export default function SharedHomeRedesign(){
 const [,params]=useRoute('/shared-home/:id'); const [,navigate]=useLocation(); const {t,language}=useLanguage();
 const [home,setHome]=useState<SharedHome|null>(null); const [tab,setTab]=useState<Tab>('home'); const [showExpense,setShowExpense]=useState(false); const [showMember,setShowMember]=useState(false); const [editingMember,setEditingMember]=useState<SharedHomeMember>(); const [showRecurring,setShowRecurring]=useState(false); const [editingRecurring,setEditingRecurring]=useState<RecurringRule>(); const [showRent,setShowRent]=useState(false); const [filter,setFilter]=useState<'all'|'category'|'member'|'month'>('all'); const [filterValue,setFilterValue]=useState(''); const monthKey=monthKeyFromDate(Date.now());
 useEffect(()=>{if(!params?.id)return;const loaded=getSharedHomeById(params.id);if(!loaded)return setHome(null);const result=materializeRecurringExpenses(loaded,monthKey);const next=result.added.length?result.home:loaded;setHome(next);if(result.added.length)saveSharedHome(next);},[params?.id,monthKey]);
 const refresh=(next:SharedHome)=>{setHome(next);saveSharedHome(next)}; const activity=(next:SharedHome,message:string)=>({...next,activity:[{id:nanoid(),message,createdAt:Date.now()},...next.activity].slice(0,100),updatedAt:Date.now()});
 const saveExpense=(e:HouseholdExpense)=>home&&refresh(activity({...home,expenses:[...home.expenses,e]},`Added ${e.name}`));
 const saveMember=(m:SharedHomeMember)=>{if(!home)return;const exists=home.members.some(x=>x.id===m.id);refresh(activity({...home,members:exists?home.members.map(x=>x.id===m.id?m:x):[...home.members,m]},exists?`Updated ${m.name}`:`Added ${m.name}`));setEditingMember(undefined)};
 const saveRecurring=(r:RecurringRule)=>{if(!home)return;const exists=home.recurringRules.some(x=>x.id===r.id);refresh(activity({...home,recurringRules:exists?home.recurringRules.map(x=>x.id===r.id?r:x):[...home.recurringRules,r]},`${exists?'Updated':'Added'} recurring ${r.name}`));setEditingRecurring(undefined)};
 const saveRent=(config:RentConfig,allocations:Record<string,number>,calculation:any,adjustment?:any)=>{if(!home)return;const period=buildRentPeriod({previous:home.rentPeriods.find(p=>p.monthKey===monthKey),monthKey,config,allocations,calculation,adjustment,now:Date.now()});refresh(activity({...home,rentConfig:config,rentPeriods:upsertRentPeriod(home.rentPeriods,period)},'Updated rent'))};
 const stats=useMemo(()=>{if(!home)return{expenses:0,rent:0,pending:0,balances:[],settlements:[] as Array<{fromMemberId:string;toMemberId:string;amount:number}>};const rent=home.rentPeriods.find(r=>r.monthKey===monthKey);const expenses=getExpenseTotals(home,monthKey).total;const balances=calculateMonthlyBalances(home,monthKey,rent);const settlements=generatePendingHouseholdSettlements(balances,home.settlements);return{expenses,rent:rent?.totalRent??0,pending:settlements.reduce((s,x)=>s+x.amount,0),balances,settlements}},[home,monthKey]);
 const visible=useMemo(()=>{if(!home)return[];let list=home.expenses.filter(e=>e.status==='active');if(filter==='category'&&filterValue)list=list.filter(e=>e.category===filterValue);if(filter==='member'&&filterValue)list=list.filter(e=>e.paidBy===filterValue||e.sharedBy.includes(filterValue));if(filter==='month'&&filterValue)list=list.filter(e=>monthKeyFromDate(e.date)===filterValue);return list},[home,filter,filterValue]);
 const memberName=(id:string)=>home?.members.find(m=>m.id===id)?.name??t('sharedHomeUnknown'); if(!home)return <div className="min-h-screen flex items-center justify-center p-6 text-sm font-semibold">{t('sharedHomeNotFound')}</div>;
 return <div className="min-h-screen bg-background pb-24"><header className="sticky top-0 z-20 bg-background border-b"><div className="max-w-5xl mx-auto px-3 py-3 flex items-center gap-2"><Button variant="ghost" size="icon" onClick={()=>navigate('/shared-homes')}><ArrowLeft size={20}/></Button><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><HomeIcon size={18}/><h1 className="font-black truncate">{home.name}</h1></div><p className="text-xs text-muted-foreground truncate">{home.address||home.homeType}</p></div><Button variant="outline" size="sm" onClick={()=>navigate(`/shared-home/${home.id}/manage`)}><Settings size={16}/><span className="hidden sm:inline">{t('sharedHomeManage')}</span></Button></div><nav className="max-w-5xl mx-auto grid grid-cols-4 border-t">{([['home',t('home')],['expenses',t('sharedHomeExpenses')],['rent',t('sharedHomeRent')],['settlement',t('sharedHomeSettlements')]] as const).map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`min-h-12 px-2 text-sm font-bold border-b-2 ${tab===id?'border-current':'border-transparent text-muted-foreground'}`}>{label}</button>)}</nav></header>
 <main className="max-w-5xl mx-auto p-4 space-y-4">
 {tab==='home'&&<><Card className="p-5"><p className="text-sm font-bold text-muted-foreground">{home.name} · {monthKey}</p><p className="text-3xl font-black mt-2">{stats.pending>0?`${t('owes')} ${money(stats.pending)}`:t('sharedHomeEveryoneSettled')}</p><div className="grid grid-cols-2 gap-3 mt-4"><Mini label={t('sharedHomeExpenses')} value={money(stats.expenses)}/><Mini label={t('sharedHomeRent')} value={money(stats.rent)}/></div></Card><div className="grid grid-cols-3 gap-2"><Quick onClick={()=>setShowExpense(true)} label={`+ ${t('sharedHomeAddExpense')}`}/><Quick onClick={()=>setShowRent(true)} label={t('sharedHomeRent')}/><Quick onClick={()=>setTab('settlement')} label={t('sharedHomeSettlements')}/></div><Section title={t('sharedHomeSettlements')}>{stats.settlements.length?stats.settlements.map((s,i)=><Row key={i} title={`${memberName(s.fromMemberId)} → ${memberName(s.toMemberId)}`} value={money(s.amount)}/>):<Empty t={t}/>}</Section></>}
 {tab==='expenses'&&<><div className="flex gap-2 flex-wrap"><Button onClick={()=>setShowExpense(true)}><Plus size={16}/>{t('sharedHomeAddExpense')}</Button><Button variant="outline" onClick={()=>{setEditingRecurring(undefined);setShowRecurring(true)}}>{t('sharedHomeRecurring')}</Button></div><Card className="p-3"><div className="flex gap-2 overflow-x-auto pb-1">{(['all','category','member','month'] as const).map(f=><Button key={f} variant={filter===f?'default':'outline'} size="sm" onClick={()=>{setFilter(f);setFilterValue('')}}>{f==='all'?t('allPayments' as any):f==='category'?t('sharedHomeCategory'):f==='member'?t('sharedHomeMembers'):t('sharedHomeCurrentMonth')}</Button>)}</div>{filter==='category'&&<select className="mt-2 w-full h-10 rounded-md border bg-background px-3" value={filterValue} onChange={e=>setFilterValue(e.target.value)}><option value="">{t('chooseCategory')}</option>{CATEGORY_VALUES.map(c=><option key={c} value={c}>{sharedHomeCategoryLabel(language,c)}</option>)}</select>}{filter==='member'&&<select className="mt-2 w-full h-10 rounded-md border bg-background px-3" value={filterValue} onChange={e=>setFilterValue(e.target.value)}><option value="">{t('sharedHomeChooseMember')}</option>{home.members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select>}</Card><Section title={t('sharedHomeExpenses')}>{visible.length?visible.slice().sort((a,b)=>b.date-a.date).map(e=><Row key={e.id} title={e.name} meta={`${new Date(e.date).toLocaleDateString('en-IN')} · ${sharedHomeCategoryLabel(language,e.category)} · ${t('sharedHomePaidBy')}: ${memberName(e.paidBy)}`} value={money(e.amount)}/>):<Empty t={t}/>}</Section><Section title={t('sharedHomeRecurringRules')}>{home.recurringRules.length?home.recurringRules.map(r=><div key={r.id} className="flex items-center gap-2"><div className="flex-1"><Row title={r.name} meta={`${r.amountMode==='fixed'?money(r.fixedAmount??0):t('sharedHomeVariable')} · ${t(`sharedHomeStatus${r.status}` as any)}`}/></div><Button size="sm" variant="outline" onClick={()=>{setEditingRecurring(r);setShowRecurring(true)}}>{t('edit')}</Button></div>):<Empty t={t}/>}</Section></>}
 {tab==='rent'&&<><div className="flex justify-end"><Button onClick={()=>setShowRent(true)}><Plus size={16}/>{home.rentPeriods.some(r=>r.monthKey===monthKey)?t('sharedHomeEditRent'):t('sharedHomeAddRent')}</Button></div><Section title={`${t('sharedHomeRent')} · ${monthKey}`}>{stats.rent?<><Row title={t('sharedHomeTotalRent')} value={money(stats.rent)}/>{(home.rentPeriods.find(r=>r.monthKey===monthKey)?.calculation??[]).map(line=><Row key={line.memberId} title={line.memberName} meta={`${t('sharedHomeShareAmount')}: ${money(line.adjustedAmount??line.calculatedAmount)}`} value={money(line.adjustedAmount??line.calculatedAmount)}/>)}</>:<Empty t={t}/>}</Section></>}
 {tab==='settlement'&&<><Card className="p-5"><p className="text-sm text-muted-foreground">{t('sharedHomePendingSettlements')}</p><p className="text-3xl font-black mt-1">{money(stats.pending)}</p></Card><Section title={t('sharedHomeSettlements')}>{stats.settlements.length?stats.settlements.map((s,i)=><Row key={i} title={`${memberName(s.fromMemberId)} ${t('owes')} ${memberName(s.toMemberId)}`} value={money(s.amount)}/>):<Empty t={t}/>}</Section><Section title={t('sharedHomeMembers')}>{stats.balances.map(b=><Row key={b.memberId} title={memberName(b.memberId)} meta={`${t('sharedHomePaidAmount')}: ${money(b.paid)} · ${t('sharedHomeShareAmount')}: ${money(b.share)}`} value={b.balance>=0?`+${money(b.balance)}`:`-${money(Math.abs(b.balance))}`}/>)}</Section></>}
 </main><SharedHomeExpenseDialog open={showExpense} kind="expense" home={home} onOpenChange={setShowExpense} onSave={saveExpense}/><SharedHomeMemberDialog open={showMember} initial={editingMember} onOpenChange={setShowMember} onSave={saveMember} onSaveMultiple={members=>{if(!home)return;const ids=new Set(members.map(m=>m.id));refresh(activity({...home,members:[...home.members.filter(m=>!ids.has(m.id)),...members]},`Added ${members.length} member(s)`))}}/><SharedHomeRecurringDialog open={showRecurring} home={home} initial={editingRecurring} onOpenChange={setShowRecurring} onSave={saveRecurring}/><SharedHomeRentDialog open={showRent} home={home} monthKey={monthKey} onOpenChange={setShowRent} onSave={saveRent}/></div>;
}
function Quick({label,onClick}:{label:string;onClick:()=>void}){return <Button variant="outline" className="min-h-11 font-bold" onClick={onClick}>{label}</Button>}; function Section({title,children}:{title:string;children:React.ReactNode}){return <Card className="p-4"><div className="flex items-center justify-between mb-2"><h2 className="font-black">{title}</h2><ChevronRight size={16} className="text-muted-foreground"/></div>{children}</Card>}; function Row({title,meta,value}:{title:string;meta?:string;value?:string}){return <div className="flex items-center gap-3 py-3 border-b last:border-0"><div className="min-w-0 flex-1"><p className="font-bold truncate">{title}</p>{meta&&<p className="text-xs text-muted-foreground truncate">{meta}</p>}</div>{value&&<p className="font-black whitespace-nowrap">{value}</p>}</div>}; function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-muted/40 p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="font-black text-lg mt-1">{value}</p></div>}; function Empty({t}:{t:(key:any)=>string}){return <p className="py-6 text-center text-sm text-muted-foreground">{t('sharedHomeNothingThisMonth')}</p>}
